export interface Reporte1 {   
    var1?: string;
    var2?: string;
    var3?: string;
    var4?: string;
    var5?: string;
    var6?: string;
    var7?: string;
    var8?: string;
    var9?: string;
    var10?: string;
    var11?: string;
    var12?: string;
    var13?: string;
    var14?: string;
    var15?: string;
    var16?: string;
    var17?: string;
    var18?: string;
    var19?: string;
    var20?: string;
    var21?: string;
    Datos?: string;
    grupo?: string;
    NombreReport?: string;
    NombreReport1?: string;
    NombreReport2?: string;
    image64?:string;
    image64_1?:string;
    image64_2?:string;
    Formula?:string;
    rmse?:string;
    r2?:string;
    prediccion?:string;
    Grado?:string;
    rmse_1?:string;
    r2_1?:string;
    rmse_2?:string;
    r2_2?:string;
    prediccion1?:string;
    Grado1?:string;
    Grado2?:string;
    modelo?:string;
    modelo1?:string;
    conclusion?: string;
    conclusion1?: string;
    conclusion2?: string;
    report1x?:number[];
    report1y?:number[];
}